### ISSUE TITLE
"Tikitoks.com" VS actual Tiktok.com

### ISSUE THREAD

**Issue by foodtourama** [instabotai/tiktok-api#11]
Now I get it... You are downloading from a "Tiktok mirror" called tikitoks, not from the actual site. And sometimes their video URLs are outdated and return a 403 error (tried the outdated link with real Firefox and gave me the same 403 error I'm getting with your scraper)... Changed the code to try to download from real Tiktok video link but no luck, it returns garbage (maybe it is expecting a real browser to redirect?)...

For example, this video from tikitoks (the "mirror" site)...
https://tikitoks.com/maskofgod/video/6784399254476688645/

Gets this video URL (which you can also get with Firefox "view page source")
https://v19.muscdn.com/8fd0785d07fc692f364e94cad273cbdb/5e2b3dab/video/tos/useast2a/tos-useast2a-ve-0068c004/3108a297c5df4940b8160db010c5300f/?a=1233&br=2652&bt=1326&cr=0&cs=0&dr=0&ds=6&er=&l=202001241255300101101021310D32F3DF&lr=&qs=0&rc=MzN1d3g0OjxqcjMzaTczM0ApaTMzaGRkZTw3N2k8PGY3OWdgLi81MHE2YmdfLS0xMTZzczMvNGBfMmM2YDAuM2E1MjI6Yw%3D

And gives me an "Error 403 Forbidden"...

But changing it to the real Tiktok video link and "view page source"...
https://www.tiktok.com/@maskofgod/video/6784399254476688645/

The SECOND match for "https://v..." gives you the correct URL for the video:
https://v16.muscdn.com/378025c34002a513ae824b67d7169ac0/5e2e878f/video/tos/useast2a/tos-useast2a-ve-0068c002/63a17984584e45bc864d1cd7a853beec/?a=1233&amp;br=1890&amp;bt=945&amp;cr=0&amp;cs=0&amp;dr=0&amp;ds=3&amp;er=&amp;l=202001270047350101101021470689FAD7&amp;lr=tiktok_m&amp;qs=0&amp;rc=MzN1d3g0OjxqcjMzaTczM0ApNDc1NGg4aTtmNzdmOzM7NGdgLi81MHE2YmdfLS0xMTZzczYuYi4zMTNfMTRjYGAvYmE6Yw%3D%3D

But I had to find that manually (using a browser and viewing page source)... still trying to retrieve the real tiktok page successfully with python...

And it has the Tiktok watermark... but at least you will be able to download something in case you get the 403 error before.

**Comment by reliefs** [comment]
I know that it works, but i have to download them without watermarks. If you find an endpoint for tiktok.com without watermarks let me know.
