### ISSUE TITLE
Crawel Url Correct

### ISSUE THREAD

**Issue by HeisSuperHan** [instabotai/tiktok-api#3]
@reliefs i see the url you extract is tiktoks.com not tiktok.com ，reliable？

**Comment by reliefs** [comment]
what's the difference ?

**Comment by HeisSuperHan** [comment]
tiktok.com is official website, but tiktoks.com is not . when you visit tiktoks.com you will see a lot of google ads. so tiktoks.com is third party website. just 's' letter difference :P
but the data from tiktoks.com is good and correct! Thankyou!

**Comment by HeisSuperHan** [comment]
sorry the url is tikitoks.com

**Comment by reliefs** [comment]
I see, yeah know i now why i had less "blocking" issue than last time.. 

Should be changed you are correct.
