### ISSUE TITLE
Is the python version 3?

### ISSUE THREAD

**Issue by design365** [instabotai/tiktok-api#7]
I use python3.6.7 to run the code:

Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    str = tiktok.download_user_video("https://www.tiktok.com/@the_d_dose/video/6758378015639538946")
AttributeError: 'Bot' object has no attribute 'download_user_video'

**Comment by design365** [comment]
I run in centos7.4

**Comment by design365** [comment]
and I use your params and header.
post to the url :
https://www.tiktok.com/@the_d_dose/video/6758378015639538946

and get the content:
{"statusCode":200,"contentType":"application/json","content":""}

the content is empty. why?

**Comment by design365** [comment]
The only thing I want to do is download the video without watermark from a video link of tiktok.
but no work

**Comment by reliefs** [comment]
I am pretty sure i fucked up when building the pip install, have you tried this from source or pip ?

**Comment by design365** [comment]
thanks for your reply ,  I did not know how to try this from source. I only do it from your guide:
********
pip install tiktok-api
********
when you resolved it ,please tell me ,thanks

**Comment by design365** [comment]
for example , the tiktok link : https://vm.tiktok.com/9ntoQj
I want a method like this:

nowaterMp4Link = tiktok.getMp4Link('https://vm.tiktok.com/9ntoQj')

that's all.  thanks

**Comment by reliefs** [comment]
what about this one ?
 api.get_video_url(video)

That one is already working..

Sorry i will not "fix" this, for the next couple of days..

You can just download source file..
make a example.py inside downloaded source file folder:

put this into it
Quickstart

from tiktokapi import bot

tiktok = bot.Bot()
 api.get_video_url(video)
