### ISSUE TITLE
It did not work.

### ISSUE THREAD

**Issue by design365** [instabotai/tiktok-api#8]
my test.py is : 
**************************
from tiktokapi import bot

tiktok = bot.Bot()
str = tiktok.download_user_videos("maskofshiva")
print(str)
****************************
and run with # python3.6 test.py 
the output is : 

0it [00:00, ?it/s]
None

nothing download .

**Comment by reliefs** [comment]
Thanks, yes you need to change the account. Fixed it.

**Comment by toyinswift** [comment]
Please what is manualSignature in tiktok.py file
does the signature expire?

**Comment by reliefs** [comment]
The signature key is really generated by ig so is not valid. This api only works with "logged out" actions and not logged in. 

Been trying to get login to work for 4 months now, with only a "few" times success and that was on new accounts.
